server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/savo
    username: savo_user
    password: savo_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

  aws:
    region: ap-southeast-1

logging:
  level:
    com.savo: DEBUG
    org.springframework.security: DEBUG