server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5232/savo
    username: savo_user
    password: savo_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id

  aws:
    region: ap-southeast-1
    s3:
      bucket: ${AWS_S3_BUCKET:savo-statements}
      max-file-size: 10485760
      url-expiration-minutes: 60
      folder-structure: "statements/{userId}/{year}/{month}/{day}"

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
      tagsSorter: alpha
    show-actuator: true

logging:
  level:
    software.amazon.awssdk: DEBUG
    com.savo.backend.service.FileStorageService: DEBUG
    com.savo: DEBUG
    org.springframework.security: DEBUG